### ISSUE TITLE
Problem on running render_movie.py

### ISSUE THREAD

**Issue by saishikawa** [andersen-lab/zika-phylogeography#1]
Hi,

I have run the "render_movie.py" to reproduce the zika-phylogeography movie on my own environment. My environment was built on Anaconda3, but based on Python 2.7;
$conda create --name py27 python=2.7 anaconda

Basemap, Pandas, and Numpy were installed on the environment, and I put "baltic.py" in the same directory with "render_movie.py". Then I run the script;
$python2.7 ./render_movie.py
and got the below error.

----
File: highest_posterior.tree
Number of objects found in tree string: 915
Micronesia
Cambodia
Cambodia
Thailand
French_Polynesia
French_Polynesia
French_Polynesia
French_Polynesia
French_Polynesia
French_Polynesia
French_Polynesia
French_Polynesia
French_Polynesia
French_Polynesia
French_Polynesia
China
China
China
China
China
China
China
China
China
China
China
China
China
China
Tonga
French_Polynesia
French_Polynesia
Haiti
Brazil
Brazil
Brazil
Brazil
USA
Brazil
Brazil
Honduras
Honduras
Mexico
USA
USA
Mexico
USA
Nicaragua
Nicaragua
Guatemala
Guatemala
Honduras
Honduras
Mexico
Honduras
Honduras
Honduras
Nicaragua
Nicaragua
Honduras
Honduras
Honduras
USA
Nicaragua
Nicaragua
Nicaragua
Nicaragua
Honduras
Honduras
Honduras
Honduras
Honduras
Honduras
Honduras
Honduras
Honduras
Honduras
Honduras
Honduras
Nicaragua
Nicaragua
Nicaragua
Nicaragua
Honduras
Nicaragua
Mexico
Mexico
Mexico
Mexico
Mexico
Mexico
Mexico
Mexico
Mexico
USA
Mexico
Mexico
Mexico
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Suriname
China
China
China
China
China
China
Dominican_Republic
Brazil
Brazil
Puerto_Rico
Puerto_Rico
Puerto_Rico
Puerto_Rico
Brazil
Puerto_Rico
USA
Puerto_Rico
USA
Puerto_Rico
French_Guiana
Suriname
Suriname
Brazil
Brazil
Brazil
Brazil
Venezuela
Brazil
Singapore
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Colombia
Mexico
Mexico
Martinique
USA
Martinique
Colombia
Peru
Peru
Colombia
Panama
Panama
Panama
Colombia
Venezuela
Venezuela
Colombia
Colombia
Panama
Colombia
Colombia
Colombia
Colombia
Colombia
Dominican_Republic
Colombia
Colombia
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Brazil
Italy
Traceback (most recent call last):
  File "render_movie.py", line 189, in <module>
    _c = scalarMap.to_rgba(groups.index(_g))
ValueError: 'Europe' is not in list
----

Do you have any advise to solve this?

Thank you for your help.

**Comment by gkarthik** [comment]
Hello,

I fixed the error and pushed the code. For some reason, I was removing Europe from the list used for the color scheme. It should work now. 

Best,
Karthik

**Comment by saishikawa** [comment]
Thank you for the fix. The problem is solved but I got new one....
----------------------------
File: highest_posterior.tree
Number of objects found in tree string: 915
Micronesia
Cambodia
Cambodia
Thailand
~
0
0
0
1
Traceback (most recent call last):
  File "render_movie.py", line 376, in <module>
    anim.save('test_zika_phylogeography.mp4',writer=FFwriter)
  File "/pasteur/entites/GEVA/miniconda3/envs/py27/lib/python2.7/site-packages/matplotlib/animation.py", line 1200, in save
    writer.grab_frame(**savefig_kwargs)
  File "/pasteur/entites/GEVA/miniconda3/envs/py27/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/pasteur/entites/GEVA/miniconda3/envs/py27/lib/python2.7/site-packages/matplotlib/animation.py", line 241, in saving
    self.finish()
  File "/pasteur/entites/GEVA/miniconda3/envs/py27/lib/python2.7/site-packages/matplotlib/animation.py", line 367, in finish
    self.cleanup()
  File "/pasteur/entites/GEVA/miniconda3/envs/py27/lib/python2.7/site-packages/matplotlib/animation.py", line 405, in cleanup
    out, err = self._proc.communicate()
  File "/pasteur/entites/GEVA/miniconda3/envs/py27/lib/python2.7/site-packages/subprocess32.py", line 724, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/pasteur/entites/GEVA/miniconda3/envs/py27/lib/python2.7/site-packages/subprocess32.py", line 1535, in _communicate
    orig_timeout)
  File "/pasteur/entites/GEVA/miniconda3/envs/py27/lib/python2.7/site-packages/subprocess32.py", line 1591, in _communicate_with_poll
    register_and_append(self.stdout, select_POLLIN_POLLPRI)
  File "/pasteur/entites/GEVA/miniconda3/envs/py27/lib/python2.7/site-packages/subprocess32.py", line 1570, in register_and_append
    poller.register(file_obj.fileno(), eventmask)
ValueError: I/O operation on closed file
--------------------------------------------------
Saving animation was failed as the file to be written was 'closed'.

Best,
Sohta

**Comment by saishikawa** [comment]
I found some forum saying that this I/O problem was happened due to the older version of 'ffmpeg' installed via pip aor conda. Actually I'm using the conda environment with Python2.7, and all other packages required by the script are installed via conda.

So, I have replaced the conda-version ffmpeg with the latest one that I locally installed from the source. However, I still have the same error...

Could you tell me which environment, you're running your script on, as well as the versions of Python and ffmpeg?

**Comment by gkarthik** [comment]
Python version 2.7
ffmpeg version 4.1

**Comment by saishikawa** [comment]
Hello,

The problem on running was solved (thank you!) and I'm working on my own data of the Chikungunya virus phylogeography.
The script works fine with my data and I got a video. But the problem is that the world map was reversed. 

I used the below lat-long information and changed some country names in the script according to this. The tree is same NEXUS format (from BEAST analysis) as the zika example. 
------
American_Samoa,-14.270972,-170.132217,Oceania
Brazil,-14.235004,-51.92528,South America
Cambodia,12.565679,104.990963,Asia
China,35.86166,104.195397,Asia
Cook,-21.236736,-159.777671,Oceania
Fiji,-16.578193,179.414413,Oceania
French_Polynesia,-17.679742,-149.406843,Oceania
India,20.593684,78.96288,Asia
Kiribati,-3.370417,-168.734039,Oceania
Nauru,-0.522778,166.931503,Oceania
New_Caledonia,-20.904305,165.618042,Oceania
Nicaragua,12.865416,-85.207229,Central America
Niue,-19.054445,-169.867233,Oceania
Pohnpei,6.892223,158.215388,Oceania
Tokelau,-8.967363,-171.855881,Oceania
Tonga,-21.178986,-175.198242,Oceania
Tuvalu,-7.109535,177.64933,Oceania
USA,37.09024,-95.712891,USA
Viet_Nam,14.058324,108.277199,Asia
Yap,9.499141,138.083472,Oceania
------------------------
Could you tell me what I can do to fix this problem?

.
![CHIK_phylogeography](https://user-images.githubusercontent.com/23167335/59514955-fd0c8300-8ef8-11e9-9484-6ee8c67f2bcd.png)

**Comment by gkarthik** [comment]
I am not sure how the map is flipped.  Could you please share the code where you call Basemap?

**Comment by saishikawa** [comment]
Hello.

The below is a link to my data and the code. 
https://drive.google.com/open?id=1Qz0zrqvPJS3HcqfmZeFSMXQrdWvM6p-v
I just modified a bit your code according to my data, and add
mpl.use('agg')
to run this code on our cluster without x screen.

thx!

**Comment by gkarthik** [comment]
Hey, I ran your script and the video rendered fine. I'm not sure if there is something weird going on with matplotlib on the cluster. 

Here is the link to the rendered video - https://www.dropbox.com/s/3pocg5bgje0qk0q/CHIK_phylogeography.mp4?dl=0

**Comment by saishikawa** [comment]
Hi. It's a good news that you got a correct video. Could you tell me the version of matplotlib and basemap in your environment? I'm using 3.0.2 & 1.1.0 respectively.

**Comment by gkarthik** [comment]
I'm using matplotlib version 2.0.0 and basemap version 1.0.07 with Python 2.7. 
I'd be surprised if the map flipped because of a version change.

**Comment by saishikawa** [comment]
Hi,

I have replaced both matplotlib and basemap versions with those you're using (2.0.0 and 1.0.07).
I finally got a correct video, where the world is not flipped as same as you could show me above. 

But I got the below warning messages on dependencies(?). I suppose you would have the same one as we're on the same environment.

/home/saishi/miniconda3/envs/py27/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py:1623: MatplotlibDeprecationWarning: The get_axis_bgcolor function was deprecated in version 2.0. Use get_facecolor instead.
  fill_color = ax.get_axis_bgcolor()
/home/saishi/miniconda3/envs/py27/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py:1767: MatplotlibDeprecationWarning: The get_axis_bgcolor function was deprecated in version 2.0. Use get_facecolor instead.
  axisbgc = ax.get_axis_bgcolor()
/home/saishi/miniconda3/envs/py27/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py:3222: MatplotlibDeprecationWarning: The ishold function was deprecated in version 2.0.
  b = ax.ishold()
/home/saishi/miniconda3/envs/py27/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py:3231: MatplotlibDeprecationWarning: axes.hold is deprecated.
    See the API Changes document (http://matplotlib.org/api/api_changes.html)
    for more details.
  ax.hold(b)

**Comment by gkarthik** [comment]
These are depreciation warnings. I think I got them too. I have since updated my version of python and matplotlib but this script should work fine despite these warnings.

**Comment by saishikawa** [comment]
OK. So, this script works perfectly now on my environment.
Thank you very much for your help!
